spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  static-path-pattern: /resources/**
  static-locations: classpath:/templates,classpath:/js
  redis:
    password: '199910'         #redis 密码
    url: 192.168.151.133   #虚拟机ip地址
    port: 6379      #Redis端口
    pool:
      maxIdle: 300    #最大空闲
      maxTotal: 1000  #连接池最大的连接数
      maxWaitMillis: 1000 #链接最大的等待时间
      minEvictableIdleTimeMillis: 300000 #最小的空闲时间  
      database: 0
      max-active: 200
      max-wait: -1
      max-idle: 8
      min-idle: 0
      timeout: 0
      store-type: none
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  datasource:
     name: test
     url: jdbc:mysql://192.168.151.133:3306/MaiMai?useUnicode=true&useJDBCCompliantTimezoneShift=true&u
     username: root
     password: Type_123
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
     filters: stat
     maxActive: 20
     initialSize: 1
     maxWait: 60000
     minIdle: 1
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:com/dao/*.xml
  type-aliases-package: com.pojo 
  config-location: classpath:mybatis-config.xml
server: 
  port: 8001
com:
  maimai:
    Lucene:
      PATH: E:\Lucene\Text