spring:
  freemarker:
    charset: UTF-8
    cache: true
    allow-request-override: false
    content-type: text/html
    template-loader-path: classpath:/templates/
    suffix: .ftl
    check-template-location: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  datasource:
     name: test
     url: jdbc:mysql:///MaiMai
     username: root
     password: type
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     filters: stat
     maxActive: 20
     initialSize: 1
     maxWait: 60000
     minIdle: 1
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:com/dao/*.xml
  type-aliases-package: com.pojo 
  config-location: classpath:mybatis-config.xml
server: 
  port: 8001